models:
 - type: main
   engine: azure
   model: gpt-4-32k-jul-18
   parameters:
    azure_endpoint: AZURE_OPENAI_ENDPOINT
    api_version: OPENAI_API_VERSION
    deployment_name: AZURE_OPENAI_DEPLOYMENT
    api_key: AZURE_OPENAI_API_KEY

rails:
  input:
    flows:
      - self check bot response
